### ISSUE TITLE
Make the developer form m2m fields multi-select (right now are dropdown single selects)

### ISSUE THREAD

**Issue by vacchiano** [vacchiano/HireDjango#1]
Right now the fields 'role_type' and 'role_level' on the Freelancer model are m2m fields however the crispy_forms & tailwind_crispy form generates this field as a dropdown single select.

**Comment by rcoffie** [comment]
![image](https://user-images.githubusercontent.com/34107104/187012543-8391bf66-7c92-497f-9453-6cf2c3075d16.png)

Seems Tailwind Crispy Doesn't support django multi Select choice field widget we can write custom css tailwind classes to style the forms .
the image above shows multiple choice select working without  tailwind_crispy_form

**Comment by vacchiano** [comment]
Good idea - I think the checkbox element for these m2m fields would be a good choice. Do you want to get started on this and then I can go in and make sure the tailwind is working properly?

**Comment by rcoffie** [comment]
ok will work on that

**Comment by vacchiano** [comment]
@rcoffie Thanks for implementing this
