### ISSUE TITLE
Use username instead of pk in profile url

### ISSUE THREAD

**Issue by ashutoshkrris** [vacchiano/HireDjango#13]
As of now, the pk is being used in the profile url.
Ideally, it would look good if we use username instead of pk.

```
path('developer/<int:pk>/', FreelancerDetailView.as_view(), name='freelancer-detail')
```

**Comment by lolrenx** [comment]
Would be a good idea to add a slug field and slugify the username then, to avoid any clash

**Comment by MichealCodez** [comment]
But I don't think there is a provision for username
Let me know if you want that
a provision for username should be made before it can be used

**Comment by ashutoshkrris** [comment]
In the views.py, we can make use of this:

```
 def freelancer_detail(request, username):
     freelancer = Freelancer.objects.get(username=username)
     context = {
         "objects": freelancer
     }
     return render(request, 'jobs/freelancer_detail/html', context)
```
For this, we will need to make change in the urls.py as well.

**Comment by vacchiano** [comment]
Thanks for opening this issue and the discussion. I think using username instead of pk is a nice implementation. Django-allauth creates a username automatically (I believe it's slug-friendly) which could be used.

The url and the slug_field on the detail view could be updated to something like this (the templates would have to be updated as well):

[Here's the django docs on this.](https://docs.djangoproject.com/en/4.1/ref/class-based-views/mixins-single-object/#django.views.generic.detail.SingleObjectMixin.slug_field)

```
class FreelancerDetailView(DetailView):
  model = Freelancer
  slug_field = 'username' #field on model
  slug_url_kwarg = 'username' #arg passed in url
```

```
urlpatterns = [
  ...
  path('developer/<slug:username>/', FreelancerDetailView.as_view(), name='freelancer-detail'), #updated
  ...
  ]
```

**Comment by ashutoshkrris** [comment]
Correct, that's a better approach.
May I work on this issue?

**Comment by vacchiano** [comment]
@ashutoshkrris yea that would be great. Please add some tests to ensure it's still functioning properly

**Comment by vacchiano** [comment]
I pulled in the PR and it all works except 1 thing:

@ashutoshkrris The only thing is that when the usernames are autogenerated from the email it keeps periods, which break the url. So may need to add a new slug field to use or override the save and replace "." with "-" or something so they are url friendly

**Comment by ashutoshkrris** [comment]
Got it @vacchiano 
Will make another PR that fixes that issue.

**Comment by lolrenx** [comment]
[django.utils.text](https://docs.djangoproject.com/en/4.1/ref/utils/#module-django.utils.text)

`django.utils.text.slugify` is what you're after
